apiVersion: apps/v1
kind: Deployment
metadata:
  name: devdiary-db-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: devdiary-db
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: devdiary-db-pv-claim
