kind: PersistentVolume
apiVersion: v1
metadata:
  name: devdiary-db-pv-volume
  labels:
    type: local
    name: devdiary-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: devdiary-db-pv-claim
  labels:
    name: devdiary-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
