version: '3.4'

services:
  app:
    image: mmredsolutions/devdiary:community
    depends_on:
      - database
      - redis
    ports:
      - "3001:3000"
    environment:
      RAILS_ENV: development
      DEVDIARY_DATABASE_DATABASE: devdiary
      DEVDIARY_DATABASE_USERNAME: devdiary
      DEVDIARY_DATABASE_PASSWORD: devdiary
      DEVDIARY_DATABASE_HOST: database
      DEVDIARY_DATABASE_PORT: 5432
      DEVDIARY_REDIS_HOST: redis
  database:
    image: postgres:11
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: devdiary
      POSTGRES_PASSWORD: devdiary
      POSTGRES_DB: devdiary
  redis:
    image: redis:5.0.7

volumes:
  postgres-data: #used by postgres
